apiVersion: v1
kind: Service
metadata:
  name: "ark-cluster"
spec:
  type: NodePort
  ports:
    {{- range .Values.instance }}
    - port: {{ .port }}
      name: {{ .map | lower | replace "_" "-" | quote }}
      protocol: TCP
    {{- end }}
    