apiVersion: v2
name: cryofall-server
version: 0.1.0

appVersion: 0.25
icon: http://press.atomictorch.com/cryofall/logos/icon_512.png
description: Cryofall game server in Kubernetes

type: application
keywords:
  - game
  - server

maintainers:
    - name: Grumpy Leopard
      email: support@grumpyleopard.com
    - name: JyeGuru
